version: '3'

services:
  api:
    container_name: 'garda-lake-wind-restapi-server'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./log:/app/log
    ports:
      - 3099:3099
    restart: 'no'
